config/routes.rb
Clansite::Application.routes.draw do

  resources :user_tanks

  resources :users do
    member do
      get 'join_clan'
      put 'update_clan_id'
      put 'leave_clan'
      put 'change_admin_status'
    end
  end

  root 'clans#index'

  resources :clans

  resources :styles

  resources :tanks

  resources :countries

  get 'signup', to: 'users#new'

  resources :sessions, only:[:new, :create]

  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'

end

app/models/tank.rb
class Tank < ActiveRecord::Base

  include RatingAverage

  validates :name, presence: true, uniqueness: true, length: {minimum: 2}
  validates :tier_number, :inclusion => 1..10

  belongs_to :country
  belongs_to :style

  has_many :user_tanks, dependent: :destroy
  has_many :users, through: :user_tanks

end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController
  before_action :set_tank, only: [:show, :edit, :update, :destroy]
  before_action :set_countries_and_styles_for_template, only: [:new, :edit, :create, :update]
  before_action :ensure_that_admin_user, except: [:index, :show]
  before_action :ensure_that_signed_in, except: [:index, :show]



  def set_countries_and_styles_for_template
    @countries = Country.all
    @styles = Style.all
  end
  # GET /tanks
  # GET /tanks.json
  def index
    @tanks = Tank.all
  end

  # GET /tanks/1
  # GET /tanks/1.json
  def show
  end

  # GET /tanks/new
  def new
    @tank = Tank.new

  end

  # GET /tanks/1/edit
  def edit
  end

  # POST /tanks
  # POST /tanks.json
  def create
    @tank = Tank.new(tank_params)

    respond_to do |format|
      if @tank.save


        create_entry_successfully(@tank, 'Tank was successfully created.', format)
      else


        modify_entry_fails(@tank, 'new', format)
      end
    end
  end

  # PATCH/PUT /tanks/1
  # PATCH/PUT /tanks/1.json
  def update
    respond_to do |format|
      if @tank.update(tank_params)

        modify_entry_successfully(@tank,  'Tank was successfully updated.' , format)
      else


        modify_entry_fails(@tank, 'edit', format)
      end
    end
  end

  # DELETE /tanks/1
  # DELETE /tanks/1.json
  def destroy
    @tank.destroy
    respond_to do |format|

      destroy_entry(tanks_url, format)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tank
    @tank = Tank.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tank_params
    params.require(:tank).permit(:name, :description, :country_id, :tier_number, :style_id)
  end
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/tanks/_form.html.erb
<%= form_for @tank, class: "form" do |f| %>
  <% if @tank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tank.errors.count, "error") %> prohibited this tank from being saved:</h2>

      <ul>
      <% @tank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.select :country_id, options_from_collection_for_select(@countries, :id, :name, selected: @tank.country_id) %>
  </div>

    <div class="field">
      <%= f.label :tier_number %><br>
      <%= f.select :tier_number, 1..10, selected: @tank.tier_number%>
    </div>

    <div class="field">
      <%= f.label :style_id %><br>
      <%= f.select :style_id, options_from_collection_for_select(@styles, :id, :name, selected: @tank.style_id) %>
    </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/tanks/_user_table.html.erb
<% if @tank.users.empty? %>

    <p>Nobody has this tank!</p>


<% else %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Clan</th>


      </tr>
      </thead>

      <tbody>
      <% @tank.users.each do |user| %>
          <tr>
            <td><%= link_to user.name, user %></td>

            <% if user.clan_id.nil? %>

                <td>Not a member of any clan!</td>

            <% else %>
                <td><%= link_to user.clan.name, clan_path(user.clan) %></td>
            <% end %>


          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

<br>

app/views/tanks/edit.html.erb
<h1>Edit tank</h1>

<%= render 'form' %>

app/views/tanks/index.html.erb
<h1>Listing tanks</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Country</th>
      <th>Tier</th>
      <th>Style</th>
      <th>Average rating</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tanks.each do |tank| %>
      <tr>
        <td><%= link_to tank.name, tank %></td>
        <td><%= tank.description %></td>
        <td><%= link_to tank.country.name, country_path(tank.country) %></td>
        <td><%= tank.tier_number %></td>
        <td><%= link_to tank.style.name, style_path(tank.style) %></td>
        <td><%= round(tank.average_rating) %></td>

        <% if check_if_allowed_to_see_link %>
            <td><%= link_to 'Edit', edit_tank_path(tank), class: "btn btn-info"  %></td>
            <td><%= link_to 'Destroy', tank, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>


        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>Number of tanks: <%= @tanks.count %></p>

<br>

<%= link_to 'New Tank', new_tank_path , class: "btn btn-success" if check_if_allowed_to_see_link %>

app/views/tanks/new.html.erb
<h1>Create new tank</h1>

<%= render 'form' %>

app/views/tanks/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @tank.name %></h1>


<p>
  <h2><strong>Description:</strong></h2>
  <%= @tank.description %>
</p>

<p>
  <h2><strong>Country:</strong></h2>
  <%= link_to @tank.country.name, country_path(@tank.country) %>
</p>

<p>
  <h2><strong>Tier:</strong></h2>
  <%= @tank.tier_number %>
</p>

<p>
  <h2><strong>Style:</strong></h2>
  <%= link_to @tank.style.name, style_path(@tank.style) %>
</p>


<p>
<h2><strong>Average rating:</strong></h2>
  <% unless @tank.users.empty? %>
    <strong><%= round(@tank.average_rating) %></strong>
  <% else %>
    <p>Tank has not yet any ratings!</p>
  <% end %>
</p>

<h2><strong>Users:</strong></h2>

<%= render 'user_table' %>

<%= link_to 'Edit', edit_tank_path(@tank), class: "btn btn-info"  if check_if_allowed_to_see_link %>