config/routes.rb
Clansite::Application.routes.draw do

  resources :user_tanks

  resources :users do
    member do
      get 'join_clan'
      put 'update_clan_id'
      put 'leave_clan'
      put 'change_admin_status'
    end
  end

  root 'clans#index'

  resources :clans

  resources :styles

  resources :tanks

  resources :countries

  get 'signup', to: 'users#new'

  resources :sessions, only:[:new, :create]

  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :name, presence: true, uniqueness: true, length: {minimum: 2}
  validates_format_of :password, :with => /\A(([0-9]|[a-z]|[A-Z])*([0-9])([0-9]|[a-z]|[A-Z])*([A-Z])([0-9]|[a-z]|[A-Z])*|([0-9]|[a-z]|[A-Z])*([A-Z])([0-9]|[a-z]|[A-Z])*([0-9])([0-9]|[a-z]|[A-Z])*)\z/, if: :password
  validates :password, length: {minimum:4}, if: :password

  belongs_to :clan
  has_many :user_tanks, dependent: :destroy
  has_many :tanks, through: :user_tanks

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :leave_clan, :join_clan, :update_clan_id, :change_admin_status]
  before_action :ensure_that_signed_in, except: [:index, :show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        create_entry_successfully(@user, 'User was successfully created.', format)
      else


        modify_entry_fails(@user, 'new', format)
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    unless @user == current_user
      redirect_to @user, notice: 'You cannot update this user'
      return
    end

    respond_to do |format|

      if user_params[:name].nil? and @user.update(user_params)

        modify_entry_successfully(@user,  'User was successfully updated.' , format)
      else


        modify_entry_fails(@user, 'edit', format)
      end

    end
  end


  def update_clan_id

    respond_to do |format|
      if @user.update(:clan_id => update_clan_params[:clan_id])


        modify_entry_successfully(@user,  "You have successfully joined in a clan!" , format)
      else


        modify_entry_fails(@user, 'join_clan', format)
      end
    end

  end



  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      session[:user_id] = nil
      respond_to do |format|

        destroy_entry(users_url, format)
      end

    else
      redirect_to users_path, notice:'You cannot delete this user'
    end


  end

  def join_clan
    @clans = Clan.all

  end

  def leave_clan
    if current_user == @user or current_user.admin


      respond_to do |format|

        if @user.update(:clan_id => nil)


          modify_entry_successfully(@user,  "You have successfully left the clan!" , format)
        else

          modify_entry_fails(@user, 'show', format)
        end
      end

    end

  end

  def change_admin_status
    @user.update_attribute :admin, (not @user.admin)

    new_status = @user.admin? ? "admin" : "normal"

    redirect_to :back, notice: "User's status was successfully set to #{new_status}"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  private
  def update_clan_params
    params.require(:user).permit(:clan_id)
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user , class: "form" do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>

    <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name , class: "form-control" %>
    </div>

  <% end %>

    <% if @clans.nil? %>
    <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: "form-control" %>

    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class: "form-control" %>

    </div>

     <% else %>

        <div class="field">
          <%= f.label :clan_id %><br>
          <%= f.select :clan_id, options_from_collection_for_select(@clans, :id, :name, selected: @user.clan_id) %>
        </div>

     <% end %>




  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/_tank_table.html.erb
<% if @user.tanks.empty? %>

    <p>User does not have any tanks!</p>



<% else %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Country</th>
        <th>Tier</th>
        <th>Style</th>

      </tr>
      </thead>

      <tbody>
      <% @user.tanks.each do |tank| %>
          <tr>
            <td><%= link_to tank.name, tank %></td>
            <td><%= tank.description %></td>
            <td><%= link_to tank.country.name, country_path(tank.country) %></td>
            <td><%= tank.tier_number %></td>
            <td><%= link_to tank.style.name, style_path(tank.style) %></td>


          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

<br>

<p><%= link_to 'Add a tank', new_user_tank_path if current_user %></p>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.name %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Clan</th>

      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>

        <% if user.clan_id.nil? %>

            <td>Not a member of any clan!</td>

        <% else %>
            <td><%= link_to user.clan.name, clan_path(user.clan) %></td>
        <% end %>

        <% unless current_user.nil?  %>

            <% if current_user == user  %>
                <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-info"  %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>

             <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p>Number of users: <%= @users.count %></p>

<br>

<%= link_to 'Create an account', new_user_path, class: "btn btn-success"  %>

app/views/users/join_clan.html.erb
<h1>Join a clan</h1>


<%= form_for @user, url: update_clan_id_user_path, method: :put , class: "form" do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



        <div class="field">
          <%= f.label :clan_id %><br>
          <%= f.select :clan_id, options_from_collection_for_select(@clans, :id, :name, selected: @user.clan_id) %>
        </div>


    <div class="actions">
      <%= f.submit "Join clan", class: "btn btn-default" %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Create an account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %></h1>

<p>
  <h2><strong>Clan:</strong></h2>


  <% if @user.clan_id.nil? %>

    <p>Not a member of any clan!</p>

    <%= link_to 'Join clan', join_clan_user_path , class: "btn btn-info" if current_user  %>

<% else %>
   <p> <%= link_to @user.clan.name, clan_path(@user.clan) %> </p>

    <%= link_to 'Leave clan', leave_clan_user_path, method: :put, data: {confirm: "Are you sure?"} , class: "btn btn-danger" if current_user %>

<% end %>
</p>

<br>

<p>
<h2><strong>Status:</strong></h2>


<% if @user.admin %>

    <p>Admin user</p>

<% else %>
    <p>Normal user</p>

<% end %>

<%= link_to 'Change status', change_admin_status_user_path, method: :put, data: {confirm: "Are you sure?"} , class: "btn btn-danger" unless current_user.nil? or !current_user.admin or current_user==@user%>
</p>

<br>


<h2><strong>Tanks:</strong></h2>

<%= render partial: 'layouts/tank_table', locals: {item: @user, name: "User"} %>

<br>

<%= link_to 'Edit', edit_user_path(@user) , class: "btn btn-info" if current_user==@user %>