config/routes.rb
Clansite::Application.routes.draw do

  resources :user_tanks

  resources :users do
    member do
      get 'join_clan'
      put 'update_clan_id'
      put 'leave_clan'
      put 'change_admin_status'
    end
  end

  root 'clans#index'

  resources :clans

  resources :styles

  resources :tanks

  resources :countries

  get 'signup', to: 'users#new'

  resources :sessions, only:[:new, :create]

  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'

end

app/models/user_tank.rb
class UserTank < ActiveRecord::Base


  validates :rating, numericality: { greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 100,
                                    only_integer: true}

  validates :user, uniqueness: {scope: :tank}

  belongs_to :user
  belongs_to :tank



end

app/controllers/user_tanks_controller.rb
class UserTanksController < ApplicationController
  before_action :set_user_tank, only: [:show, :edit, :update, :destroy]

  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /user_tanks
  # GET /user_tanks.json
  def index
    @user_tanks = UserTank.all
  end

  # GET /user_tanks/1
  # GET /user_tanks/1.json
  def show
  end

  # GET /user_tanks/new
  def new
    @user_tank = UserTank.new
    @tanks = set_tanks
  end

  def set_tanks

    if current_user.tanks.count == Tank.count
      return nil
    else
      return Tank.all.reject{|tank| tank.users.include? current_user}
    end
  end

  # GET /user_tanks/1/edit
  def edit

  end

  # POST /user_tanks
  # POST /user_tanks.json
  def create
    @user_tank = UserTank.new(user_tank_params)
    @user_tank.user = current_user

    respond_to do |format|
      if @user_tank.save
        format.html { redirect_to @user_tank, notice: 'The tank was successfully added to your account!' }
        format.json { render action: 'show', status: :created, location: @user_tank }
      else
        @tanks = set_tanks
        format.html { render action: 'new' }
        format.json { render json: @user_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tanks/1
  # PATCH/PUT /user_tanks/1.json
  def update
    respond_to do |format|
      if @user_tank.user == current_user or current_user.admin

        if @user_tank.update(user_tank_params)
          format.html { redirect_to @user_tank, notice: 'User tank was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user_tank.errors, status: :unprocessable_entity }
        end

      else
        format.html { redirect_to @user_tank, notice:'You cannot update this tank'}

      end
    end
  end

  # DELETE /user_tanks/1
  # DELETE /user_tanks/1.json
  def destroy
    if @user_tank.user == current_user or current_user.admin

      @user_tank.destroy

      respond_to do |format|
        format.html { redirect_to user_tanks_url }
        format.json { head :no_content }
      end

    else

      respond_to do |format|
        format.html { redirect_to @user_tank, notice:'You cannot delete this tank'}

      end
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user_tank
    @user_tank = UserTank.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_tank_params
    params.require(:user_tank).permit(:user_id, :tank_id, :rating)
  end
end

app/helpers/user_tanks_helper.rb
module UserTanksHelper
end

app/views/user_tanks/_form.html.erb
<%= form_for @user_tank, class: "form" do |f| %>
  <% if @user_tank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_tank.errors.count, "error") %> prohibited this user_tank from being saved:</h2>

      <ul>
      <% @user_tank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <% if @user_tank.new_record? %>

        <% if @tanks.nil? %>

            <p> You already have all the tanks! </p>

        <% else %>


            <div class="field">
              <%= f.label :tank_id %><br>
              <%= f.select :tank_id, options_from_collection_for_select(@tanks, :id, :name) %>

            </div>

            <div class="form-group">
              <%= f.label :rating %><br>
              <%= f.number_field :rating , class: "form-control"%>
            </div>

            <div class="actions">
              <%= f.submit "Add a tank", class: "btn btn-default"  %>
            </div>

        <% end %>


     <% else %>

        <div class="form-group">
          <%= f.label :rating %><br>
          <%= f.number_field :rating , class: "form-control"%>
        </div>

        <div class="actions">
          <%= f.submit "Edit a tank" , class: "btn btn-default" %>
        </div>


    <% end %>



<% end %>

app/views/user_tanks/edit.html.erb
<h1>Editing tank: <%= @user_tank.tank.name %></h1>

<%= render 'form' %>

app/views/user_tanks/index.html.erb
<h1>Listing users and their tanks</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Tank</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_tanks.each do |user_tank| %>
      <tr>
        <td><%= link_to user_tank.user.name, user_path(user_tank.user) %></td>
        <td><%= link_to user_tank.tank.name, tank_path(user_tank.tank) %></td>
        <td><%= user_tank.rating %></td>
        <td><%= link_to 'Show', user_tank, class: "btn btn-default" %></td>

        <% unless current_user.nil?  %>
            <% if current_user == user_tank.user or current_user.admin %>
                <td><%= link_to 'Edit', edit_user_tank_path(user_tank), class: "btn btn-info"  %></td>
                <td><%= link_to 'Destroy', user_tank, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>
            <% end %>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>Users have <%= pluralize( @user_tanks.count, 'tank') %> </p>

<br>

<%= link_to 'Add a new tank', new_user_tank_path , class: "btn btn-success" if current_user %>

app/views/user_tanks/new.html.erb
<h1>Add new tank</h1>

<%= render 'form' %>

app/views/user_tanks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><strong>User:</strong></h2>
  <%= link_to @user_tank.user.name, user_path(@user_tank.user) %>
</p>

<p>
 <h2><strong>Tank:</strong></h2>
  <%= link_to @user_tank.tank.name, tank_path(@user_tank.tank) %>
</p>

<p>
  <h2><strong>Rating:</strong></h2>
  <%= @user_tank.rating %>
</p>


<%= link_to 'Edit', edit_user_tank_path(@user_tank) , class: "btn btn-info" if check_if_allowed_to_see_link %>