config/routes.rb
Clansite::Application.routes.draw do

  resources :user_tanks

  resources :users do
    member do
      get 'join_clan'
      put 'update_clan_id'
      put 'leave_clan'
      put 'change_admin_status'
    end
  end

  root 'clans#index'

  resources :clans

  resources :styles

  resources :tanks

  resources :countries

  get 'signup', to: 'users#new'

  resources :sessions, only:[:new, :create]

  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Clans', clans_path %></li>
<li><%= link_to 'Tanks', tanks_path %></li>
<li><%= link_to 'Styles', styles_path %></li>
<li><%= link_to 'Countries', countries_path %></li>
<li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Tanks of Users', user_tanks_path %></li>

<% if current_user.nil? %>

   <li><%= link_to 'Signup', signup_path  %></li>
   <li><%= link_to 'Signin', signin_path  %></li>

<% else %>

   <li><%= link_to current_user.name, current_user %></li>

   <li><%= link_to 'Signout', signout_path, method: :delete %></li>

<% end %>

app/views/layouts/_tank_table.html.erb
<% if item.tanks.empty? %>

    <p><%= name %> does not have any tanks!</p>



<% else %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Country</th>
        <th>Tier</th>
        <th>Style</th>
        <th>Average rating</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% item.tanks.distinct.each do |tank| %>
          <tr>
            <td><%= link_to tank.name, tank %></td>
            <td><%= tank.description %></td>
            <td><%= link_to tank.country.name, country_path(tank.country) %></td>
            <td><%= tank.tier_number %></td>
            <td><%= link_to tank.style.name, style_path(tank.style) %></td>
            <td><%= round(tank.average_rating) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Clansite" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Clansite" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class=".container-fluid">

       <%= render 'layouts/messages' %>

      <div class="row">
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>

      <div class="row">

        <div class="col-md-6">
          <img src="http://clans.worldoftanks.eu/media/clans/emblems/cl_218/500000218/emblem_64x64.png" width="100">

        </div>

        <div class="col-md-6">

          <img src="http://clans.worldoftanks.eu/media/clans/emblems/cl_360/500007360/emblem_64x64.png" width="100">
        </div>
      </div>

    </main>
  </body>
</html>